### ISSUE TITLE
Root "Documentation" page doesn't show nav tree on mobile 

### ISSUE THREAD

**Issue by loewenstein** [gardener/documentation#110]
There's not much more to say. If I select "Documentation" in the landing page's menu the only thing that shows up it the "Create an issue" page. 

---
Page: [](https://github.com/gardener/documentation/edit/master/website/)
don't remove the link to the page. It's required for the processor

**Comment by ialidzhikov** [comment]
Duplicate of https://github.com/gardener/documentation/issues/106

**Comment by loewenstein** [comment]
A duplicate indeed.
