### ISSUE TITLE
API reference pages are missing

### ISSUE THREAD

**Issue by vpnachev** [gardener/documentation#115]
**What happened**:
I tried to open
- https://gardener.cloud/documentation/references/core
- https://gardener.cloud/documentation/references/extensions
- https://gardener.cloud/documentation/references/settings

But for all of them I get an error 
![image](https://user-images.githubusercontent.com/6798531/86379844-06979300-bc94-11ea-8ee1-d1f8d4c7dace.png)

**What you expected to happen**:
API reference pages to be available.

**How to reproduce it (as minimally and precisely as possible)**:
Open one of the three links mention above.

**Anything else we need to know**:

**Environment**:

**Comment by g-pavlov** [comment]
fixed with [[int] fixed links on api references section page](https://github.com/gardener/documentation/commit/2aa13534fc0efdbb43d11884dee05c1436456233)
