### ISSUE TITLE
Gardener Project Documentation Material

### ISSUE THREAD

**Issue by g-pavlov** [gardener/documentation#118]
# Documentation Types overview
The following table summarizes the planned types of documentation. 

| Gardener Content Type | Definition | Example|
|:----|:-----|:-----|
| How-to Guide |  Describes how to perform a complex, task that requires to complete smaller tasks. | [Upgrading kubeadm clusters](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) |
| Tutorial | A step-by-step description that allows users to complete an example task with the goal to learn the details of a given feature. | [Stateless Applications](https://kubernetes.io/docs/tutorials/stateless-application/) |
| Concept |  Introduce a functionality or concept, covers background information. | [Services](https://kubernetes.io/docs/concepts/services-networking/service/) |
| Trial | [Planned] Collection of all other content types to cover a big topic. (Currently it's not possible to reuse content, for example, a tutorial used in a trial must be copied to the trial.) | [Custom Networking](https://docs.oracle.com/javase/tutorial/networking/TOC.html) |
| Reference | Provide a reference, for example, list all command line options of `gardenctl` and what they are used for. | [Overview of kubectl](https://kubernetes.io/docs/reference/kubectl/overview/)| 

See the  [Documentation Contributors Guide](https://gardener.cloud/contribute/docs/) for more details on documentation types, how to produce and contribute them.

# Target Audience
- **Gardener operators/SRE (Operators):** Operate a public or private service or service in "fenced" environment.  Their scope is primarily installation, update/upgrade and operation of the service and its key components, tools references.
- **Gardener (extension) developers (Developers):** Develop extensions for Gardener for e.g. more cloud or DNS providers. Their scope is Gardener's architecture and extensibility framework.
- **Gardener cluster users (Users):** Use the Gardener managed service to create and operate clusters on demand. Primary concerns are day1/day2 operations in a cluster. Includes also automated operators, although they deserve special attention and sections as in fact that's the predominant way that the service will be used beyond trying it out (manually).

**Kubernetes Application Developers** role is not in scope for the technical documentation, but is most welcome in technical blogs as long as Gardener is concerned as a topic.

# Call for content

## Guides
- **Concepts**
  - **Overview** (Kubernetes managing Kubenetes, applying k8s principles to cluster management, controller (operator) pattern, control plane hosting, key components, garden, seeds and shoots)
  - **Gardener Cluster Management Control Plane**
    - **[API server](https://github.com/gardener/gardener/blob/master/docs/concepts/apiserver.md)**
    - **[Scheduler](https://github.com/gardener/gardener/blob/master/docs/concepts/scheduler.md)**
    - **[Controller Manager](https://github.com/gardener/gardener/blob/master/docs/concepts/controller-manager.md)**
  - **[Gardenlet](https://github.com/gardener/gardener/blob/master/docs/concepts/gardenlet.md)**
  - **[Seed admission controller](https://github.com/gardener/gardener/blob/master/docs/concepts/seed-admission-controller.md)**
  - **[Seed Bootstrapping](https://github.com/gardener/gardener/blob/master/docs/usage/seed_bootstrapping.md)**
  - **Infrastructure Providers**
  - **Networking**
    - **[Network policies](https://github.com/gardener/gardener/blob/master/docs/concepts/network_policies.md)**
    - **Reverse shoot to seed tunneling**
    - **[SNI passthrough proxy for kube-apiservers](https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md)**
  - **Worker Nodes Management**
  - **DNS and certificates management**
  - **Scaling**
  - **[Control plane migration](https://github.com/gardener/gardener/blob/master/docs/proposals/07-shoot-control-plane-migration.md)**
  - **[Backup and Restore](https://github.com/gardener/gardener/blob/master/docs/concepts/backup-restore.md)**
- **Installation** [new|tbd] how to use the new Gardener landscaper 
  - **Local installation**
  - **Public hyperscalers**
    - **...**
  - **Private hyperscalers**
    - **...**
  - **Manual installation**
    - **[Gardener](https://github.com/gardener/gardener/blob/master/docs/deployment/setup_gardener.md)**
    - **[Gardenlet](https://github.com/gardener/gardener/blob/master/docs/deployment/deploy_gardenlet.md)**
    - **[Add nodes](https://gardener.cloud/documentation/guides/install_gardener/add-node-to-cluster/)**
    - **[Setting up seed cluster](https://gardener.cloud/documentation/guides/install_gardener/setup-seed/)**
    - **[Hardening the community setup](https://gardener.cloud/documentation/guides/install_gardener/secure-setup/)**
  - **[Feature gates](https://github.com/gardener/gardener/blob/master/docs/deployment/feature_gates.md)**
  - **[Container images](https://github.com/gardener/gardener/blob/master/docs/deployment/image_vector.md)**
- **Operations** ops guide + [Troubleshooting](https://gardener.cloud/documentation/guides/monitoring_and_troubleshooting/)
- **Usage**
  - **Client tools**
    - **[Authenticating with Identity Provider](https://gardener.cloud/documentation/guides/client_tools/oidc-login/)**
    - **...**
  - **Account onboarding** incl. non-managed account resources
  - **Working with projects** [new] in a project in dashboard UI.
  - **Organizing access control** [new] in a project in dashboard UI.
  - **Setting up ingress** [new] (also with custom domain) Usually, that's one of the first tasks to do for a new cluster. There's a [tutorial](https://gardener.cloud/documentation/tutorials/shoot_istio_dns_certs/) that shows that with istio but a simpler and focused guide may help too and also *complete* the learning trail.
  - **External DNS management** [new] - based on [that](https://gardener.cloud/documentation/guides/administer_shoots/dns_names/) but we need extended operations only here. See also #119 
  - **[Certificates management](https://gardener.cloud/documentation/guides/administer_shoots/x509_certificates/)**
  - **Monitoring and alerts** [new] what is monitored, how to find the monitoring ui (grafana), how to make best use of it and for what.  
  - **[Logging](https://github.com/gardener/logging/blob/master/docs/usage/README.md)** 
  - **[Hibernation](https://gardener.cloud/documentation/guides/administer_shoots/hibernate-cluster/)** [update]
  - **Working with worker pools**: describe shortly how worker nodes relate to account resources, how to use them in dashboard, how to manage them manually. _Autoscaling_ can be merged here if not too large.
  - **Autoscaling** - describe how to influence it to benefit and in what ways, and how not to get in its way
  - **[Cluster maintenance](https://gardener.cloud/documentation/guides/administer_shoots/maintain-shoot/)**
  - **[Trigger shoot operations](https://gardener.cloud/documentation/guides/administer_shoots/trigger-shoot-operations/)**
  - **Kubeconfig rotation** why would users need that and how to do it in the Dashboard
  - **Operating with kubectl** [new] - command line tasks with Gardener clusters - projects, access control, ...
  - **Web Terminal** [new] - a short use of the web terminal feature
- **Extensions**
  - **[Overview](https://github.com/gardener/gardener/blob/master/docs/extensions/overview.md)**
  - **[Extension controller registration](https://github.com/gardener/gardener/blob/master/docs/extensions/controllerregistration.md)**
  - **[Cluster](https://github.com/gardener/gardener/blob/master/docs/extensions/cluster.md)**
  - **Extension Points**
    - **...**
  - **Project roles**
- **Development**
  - **[Code contributors guidelines](https://github.com/gardener/documentation/blob/master/CONTRIBUTING.md)** [needs update]
  - **[Gardener Enhancement Process](https://github.com/gardener/gardener/blob/master/docs/proposals/README.md)**
  - **Gardener Enhancement Proposals**
    - **...**
  - **[Integration testing](https://github.com/gardener/gardener/blob/master/docs/testing/integration_tests.md)**
  - **...**

All material except those in "Concepts" are *How-to Guides*.
"Concepts" are *Concept* type of material.

## Tutorials

- **Developing your first extension**
- **Create clusters in restricted environment**
- **Gardener 101**
  - **Installing your first Gardener in cluster**
  - **Registering a seed cluster** (?)
  - **Working with projects**
  - **Creating your first shoot cluster**
  - **Deploying a Kubernetes application** 
  - **...** 
- **...**

**Comment by vlerenc** [comment]
I am not quite sure where the difference is between "How-to Guide" and "Tutorial" and why we would add "Trial".

**Comment by Kristian-ZH** [comment]
As we had changed the documentation structure in the past and now the website is structured by components, I do not think that this issue is still relevant

/close
