### ISSUE TITLE
Local preview doesn't work correctly

### ISSUE THREAD

**Issue by g-pavlov** [gardener/documentation#157]
**What happened**:
With the shift to `docforge` some folders were removed from documentation because they are fetched by `docforge`. Consequently when doing `make serve` for local preview they are missing form the website because the step with docforge build has not been executed. The only way round that is to use docforge, before doing local preview, similar to what we do in the automated central build. That unfortunately, makes it difficult to support live changes, but is still a way to preview before submitting.

**What you expected to happen**:
Supply the documentation manifest for which we want to see preview and have it built and shown for us. 

/priority critical

**Comment by g-pavlov** [comment]
cc @swilen-iwanow

**Comment by Kristian-ZH** [comment]
I do not see easy solution to address this issue. As the docforge works with Manifest, the changes should be pushed somewhere and the Manifest should be linking them before executing the docforge command. I will close this issue for now, but we will keep in our mind this case as a further improvement, where we can spend some more time
