### ISSUE TITLE
oidc-login documentation looks very outdated

### ISSUE THREAD

**Issue by uvwild** [gardener/documentation#161]
**What would you like to be added**:
The Authentication documentation is very outdated.
https://gardener.cloud/documentation/guides/client_tools/oidc-login/

**Why is this needed**:
It references auth0.com
but the information needed to configure this is insufficient in many places and needs to be reviewed from someone experienced.
Trying to match auth0 page configuration with the documentation is frustrating because too much is missing or outdated.
That' s the thing with examples. they should work.

**Comment by vasu1124** [comment]
Every identity provider is different in technology, somewhat in terminology and Ux. 

The relevant sections in the Gardener documentation is not about configuring the IdP (where auth0 was only used as a generic example). The relevant information is about a) generally needing to configure a kubectl oidc plugin and the attributes of the kubeconfig, and b) the options in the Gardener shoot specification.

Dependig on the used identity provider, you might even get a specialized oidc plugin where configuration of the kubeconfig is different. Also, depending on the provider setup, the configuration of scopes and usernameClaim etc. can be very different. The information needed to configure all possible providers and setups is surely out of scope of the Gardener documentation.

The auth0 documentation works and should be used, lastly, only as a guiding principle.
