### ISSUE TITLE
Contributing.md small link change, replace maintainers with codeowners

### ISSUE THREAD

**Issue by fatihpense** [gardener/documentation#2]
Hi!
First of all, thank you for open-sourcing your efforts!

I was reading contributing guide:
https://github.com/gardener/documentation/blob/master/CONTRIBUTING.md

It seems this is 404
https://github.com/gardener/documentation/blob/master/MAINTAINERS.md

Maintainers file changed in a recent commit and the repo is also different:
https://github.com/gardener/gardener/blob/master/CODEOWNERS

Regards, 
Fatih

**Comment by msohn** [comment]
I fixed the link and clarified that you should look at the CODEOWNERS file of the repository you want to contribute to
