### ISSUE TITLE
Documentation issue on page "https://github.com/gardener/documentation/wiki/Architecture"

### ISSUE THREAD

**Issue by freegroup** [gardener/documentation#20]
the *architecture* page didn't really show the architecture of the gardner. I think this should be updated

---
Page: [https://github.com/gardener/documentation/wiki/Architecture](https://github.com/gardener/documentation/wiki/Architecture)
don't remove the link to the page. It's required for the processor

**Comment by Kristian-ZH** [comment]
Please open this issue in the gardener repo as the page is a part of it

/close
