### ISSUE TITLE
Find a place to include stargazer chart

### ISSUE THREAD

**Issue by vasu1124** [gardener/documentation#22]
## Stargazers over time

[![Stargazers over time](https://starcharts.herokuapp.com/gardener/gardener.svg)](https://starcharts.herokuapp.com/gardener/gardener)

**Comment by Kristian-ZH** [comment]
You can discuss it with Nikolay if it is still a relevant

/invite @n-boshnakov

**Comment by JordanJordanov** [comment]
obsolete
