### ISSUE TITLE
Typo in Guides

### ISSUE THREAD

**Issue by tedteng** [gardener/documentation#230]
Typo in the guides  
https://gardener.cloud/documentation/guides/administer_shoots/
![image](https://user-images.githubusercontent.com/42234376/115503965-cf898100-a2a9-11eb-9eac-c235efecc546.png)

**Comment by BeckerMax** [comment]
Hi Ted, thanks for noticing.
could you provide a fix in form of a PR for this repo?

**Comment by tedteng** [comment]
sure, I will assign it.

**Comment by tedteng** [comment]
done https://github.com/gardener/website/pull/7
Not familiar with the document structure let me know if I am not on the right approach.

**Comment by BeckerMax** [comment]
Hi Ted,
the repo you opened a PR in contains auto-generated files. See the picture in https://github.com/gardener/website .
Therefore, you need to change it in this repository. I think the following file has the formatting problem:
https://github.com/gardener/documentation/blob/master/website/documentation/guides/administer_shoots/gardener_azure/index.md

Rename  `index.md` -> `_index.md` and add a title section like in the other documents:
https://raw.githubusercontent.com/gardener/documentation/master/website/documentation/guides/administer_shoots/gardener_aws/_index.md
