### ISSUE TITLE
Auditing Kubernetes for Secure Setup

### ISSUE THREAD

**Issue by sTb1337** [gardener/documentation#255]
svg image is not shown. 

`<object type="image/svg+xml" data="./images/teaser.svg" style=";visibility:hidden; margin: 3rem auto;display: block;" class="inline reveal-fast drop-shadow"></object>`

I am using Safari 14.1 on macOS (Catalina).

**Comment by Kristian-ZH** [comment]
I think that this issue is already fixed.
Reopen if you see it again.

/close
