### ISSUE TITLE
References to internal sap webservers in documentation

### ISSUE THREAD

**Issue by freegroup** [gardener/documentation#27]
the documentation contains at some places references to wdf.sap.corp domain.
Remove this if the we have moved the content to the public github.

**Comment by jonathanbaker7** [comment]
This ticket is now 20 days old.  If it is not resolved by November 4, 2018, I will revoke permissions for the project and move it back for review.  Please resolve immediately!

**Comment by freegroup** [comment]
fixed. sorry for the delay.
