### ISSUE TITLE
☂️-Issue for updating the "Create a kubernetes cluster" tutorials

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/documentation#287]
/area documentation
/kind enhancement

**What would you like to be added**:
The `Create a kubernetes cluster in <provider> with Gardener` tutorials are currently outdated. 

- The screenshots in these guides are from old versions of the Gardener dashboard, so it makes sense to update the screenshots.
- There were also suggestions to rework the cloud provider specific steps to do not include screenshots but rather links to the cloud provider documentation itself to make our tutorials less likely to get outdated when the cloud provider UI changes.
- Improve the sections. 
  - Currently the guides have a section for `Prerequisites`, then the steps start right away. I guess the steps should be in a section called `Procedure`.
  - Currently the guides end in awkward manner. We can add a section called `Results` that basically summarizes the what we achieved just now and what's next.

---

These are the tutorials that need update:
- [x] AWS - https://gardener.cloud/docs/guides/administer_shoots/gardener_aws/ -> https://github.com/gardener/gardener-extension-provider-aws/pull/431
- [x] GCP - https://gardener.cloud/docs/guides/administer_shoots/gardener_gcp/ -> https://github.com/gardener/gardener-extension-provider-gcp/pull/341
- [x] Azure - https://gardener.cloud/docs/guides/administer_shoots/gardener_azure/ -> https://github.com/gardener/gardener-extension-provider-azure/pull/402
- [x] Alicloud - https://gardener.cloud/docs/guides/administer_shoots/gardener-alibaba/ - https://github.com/gardener/gardener-extension-provider-alicloud/pull/376

**Why is this needed**:
To have our documentation up to date.

**Comment by Kristian-ZH** [comment]
Thanks for the issue @ialidzhikov 
Where the update should happen? In the documentation repo, and after that to move the new documents to the extensions or directly in the extension repos when all of my PRs are merged?

/invite @n-boshnakov Can you please update the listed documents.

**Comment by ialidzhikov** [comment]
I am closing this one as all subtasks are completed (4/4).

/close
