### ISSUE TITLE
nodejs script does not work

### ISSUE THREAD

**Issue by JensHaley** [gardener/documentation#39]
When I followed the following instructions:

# crawl remote markdown content 
#
node ./node/index.js 

I first get an error message that node is not an available command. In Ubuntu it's "nodejs" unless you download "node" as part of the nodejs-legacy package.

No matter if I use "nodejs" or "node" after installation I get the following error message after executing ./node/index.js:

~/myGithub/05_public_gardener/website-generator$ nodejs ./node/index.js 
/sapmnt/home1/dXXXXXX/myGithub/05_public_gardener/website-generator/node/index.js:35
        let content = fm(fs.readFileSync(file, 'utf8'))
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

So does this work at all for local installations?

**Comment by freegroup** [comment]
which version of node did you install?

```
 node --version
```

**Comment by JensHaley** [comment]
npm -version: 3.5.2
nodejs -v: 4.2.6
node -version: 4.2.6

There is apparently a name conflict in Debian linux for "node", that's why "sudo apt install npm" installs "nodejs" ([more info](https://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu)). Anyway, the version is **4.2.6** for both.

I wouldn't know how to install a more recent one.

**Comment by freegroup** [comment]
oooh - 


Node.js 4.2.6 | Argon | 2016-01-21 | 4.5.103.35 | 2.14.12 | 46
-- | -- | -- | -- | -- | --



:-)

at least nodejs 8.6 is required.

**Comment by JensHaley** [comment]
ok, now I was able to install nodejs version 8.15 and it works - thanks

Maybe it would be worth mentioning this in the documentation for the generator.
