### ISSUE TITLE
Bulleted list on https://github.com/gardener/documentation/wiki/Architecture. 

### ISSUE THREAD

**Issue by je-hal** [gardener/documentation#40]
Please add a line before the bulleted list to solve issue on external Web page

This page is also pulled into the external Gardener documentation.
Due to the missing newline, the bulleted list is not rendered:
    https://gardener.cloud/030-architecture/
    
I added a newline and a local test showed that this solves the problem. I don't have permissions to create a pull request for the changed wiki page.

**Comment by JensHaley** [comment]
Thanks!
