### ISSUE TITLE
Documentation issue on page "050-tutorials/content/howto/kubectl-apiserver/_index.md"

### ISSUE THREAD

**Issue by shahar-h** [gardener/documentation#46]
kubectl has native support of jsonpath. You can use it in your tutorials instead of jq.

Get the service account:
instead of:
SERVICEACCOUNT=$(kubectl get serviceaccount deploy-user -n default -o json | jq -r .secrets[0].name)
use:
SERVICEACCOUNT=$(kubectl get serviceaccount deploy-user -n default -o=jsonpath={.secrets[0].name}

Generate a token for the serviceaccount:
instead of:
TOKEN=$(kubectl get secret -n default $SERVICEACCOUNT  -o json | jq -r .data.token | base64 -D)
use:
TOKEN=$(kubectl get secret -n default $SERVICEACCOUNT -o=jsonpath={.data.token} | base64 -D)

---
Page: [050-tutorials/content/howto/kubectl-apiserver/_index.md](https://github.com/gardener/documentation/edit/master/website/documentation/050-tutorials/content/howto/kubectl-apiserver/_index.md)
don't remove the link to the page. It's required for the processor

**Comment by ialidzhikov** [comment]
Nice catch. Could you please file PR with the proposed improvements? Thanks in advance.
