### ISSUE TITLE
Denying all traffic from namespace

### ISSUE THREAD

**Issue by Skarlso** [gardener/documentation#65]
Hi.

The networkpolicy here: documentation/website/documentation/050-tutorials/content/howto/network-isolation/_index.md

It should be noted that this will also deny all internet based traffic in those pods as well.

**Comment by ialidzhikov** [comment]
Nice catch! Can you please file PR about it?

**Comment by Skarlso** [comment]
Sure thing. I'll do that first thing tomorrow. 👌👍

**Comment by ialidzhikov** [comment]
Fixed with #66.

**Comment by Skarlso** [comment]
Thank you! :)
