### ISSUE TITLE
AdBlockPlus extension hides the menu items on the landing page

### ISSUE THREAD

**Issue by shturec** [gardener/documentation#69]
[AdBlockPlus](https://adblockplus.org/) extension hides the menu items on the landing page because it detects an element with class `social-items`, which is blacklisted here: https://easylist-downloads.adblockplus.org/fanboy-social.txt (one of the AdBlockPlus built-in blacklists).   
See here: https://github.com/gardener/website/blob/master/docs/index.html#L28

This could be easily avoided by whitelisting gardener.cloud, or excluding this blacklist in general or not using AdBlockPlust. However, it happens to be the most popular addblocker with impressive user base in the range of tens of millions so the chance that a user of theirs tries to land on gardener.cloud is substantial. Therefore, this breaks the experience for users inquiring about Gardener and this is not good marketing. On top, it's not so visible that the menu is actually hidden due to addblock blacklisting. The first thing that comes to mind is that it's simply not there. That also contributes to a negative and unjustified experience as people may leave with the conclusion there are is simply no documentation for example.

Perhaps, changing the class to something less addblockable, even if less semantic too, is a better strategy here.

Also note that all links in the social buttons are wrong, featuring `gardener.clound` instead of `gardener.cloud`.

**Comment by ialidzhikov** [comment]
Thanks for reporting.

**Comment by EmoinLanyu** [comment]
Thanks a lot for clarifying! I just noticed the same issue in Chrome lols, worked around it using incognito mode, didn't think it was because of ABP tho.
