### ISSUE TITLE
Takeover the docs for installing knative on Gardener

### ISSUE THREAD

**Issue by g-pavlov** [gardener/documentation#77]
There are [changes coming up](https://groups.google.com/d/msgid/knative-dev/D62AF7A8-91C7-4A5C-BDDE-8D80E894AF5A%40vmware.com) to the https://knative.dev/docs/install and documentation there needs to move away and just be linked. that includes the [installation guide for Gardener](https://knative.dev/docs/install/knative-with-gardener/). 

The changes are planned for the 0.13 documentation. I can't find release plans but in the notification it's noted on 6th of February that we are "about three weeks from there". So deadline should be end of February.

- [x] Host the installation guide on gardener.cloud 
- [x] Make a pull request in knative to update the docs with the new location
- [x] Update the guide as required for the latest Gardener

**Comment by g-pavlov** [comment]
https://gardener.cloud/050-tutorials/content/howto/knative-install/

**Comment by shturec** [comment]
https://github.com/knative/docs/pull/2232

**Comment by g-pavlov** [comment]
https://github.com/knative/docs/pull/2232

**Comment by g-pavlov** [comment]
The pull request is merged in knative master branch: https://knative.dev/development/knative-offerings/ (change to pre-release)
