### ISSUE TITLE
Slack link

### ISSUE THREAD

**Issue by Tombar** [gardener/documentation#8]
Hello, 

Just a friendly note that the slack link in the website points to https://gardener-cloud.slack.com/ which doesn't provide a way to get an invite/register into the slack channel.

**Comment by msohn** [comment]
see #9

**Comment by vasu1124** [comment]
@tmikaeld <a href="https://github.com/gardener" target="_blank"> does not work for you?

**Comment by tmikaeld** [comment]
Clicking these buttons on latest Firefox results in nothing happening (Works in Chrome):

![image 2018-05-18 at 11 02 38 am](https://user-images.githubusercontent.com/907195/40226138-33076158-5a8b-11e8-8a25-929552d86fbc.png)
