### ISSUE TITLE
Documentation issue on page "050-tutorials/content/howto/dns_names/_index.md"

### ISSUE THREAD

**Issue by rrashidov** [gardener/documentation#97]
```
So, far only the external DNS domain of a shoot (already used for the kubernetes api server and ingress DNS names) can be used for managed DNS names.
```

should be

```
So far only the external DNS domain of a shoot (already used for the kubernetes api server and ingress DNS names) can be used for managed DNS names.
```

---
Page: [050-tutorials/content/howto/dns_names/_index.md](https://github.com/gardener/documentation/edit/master/website/documentation/050-tutorials/content/howto/dns_names/_index.md)
don't remove the link to the page. It's required for the processor

**Comment by ialidzhikov** [comment]
@rrashidov , can you propose PR about it?

**Comment by tehcyx** [comment]
Just found the same issue, seems still broken.

**Comment by n-boshnakov** [comment]
The page in question has been moved to a different repository and its content has been modified. In doing so this issue has been fixed, so I will be closing it.

**Comment by n-boshnakov** [comment]
The page in question has been moved to a different repository and its content has been modified. In doing so this issue has been fixed, so I will be closing it.
